<<<<<<< HEAD
- repo: https://github.com/visionn/crespi
  hooks:
    - id: prettier
    - files: '*.js'
=======
<<<<<<< HEAD
- repo: https://github.com/cubisti/crespi-tour
  hooks:
    - id: prettier
    - files: '*.js'
=======
- repo: https://github.com/cubisti/crespi-tour
  hooks:
    - id: prettier
    - files: '*.js'
>>>>>>> 0d0795dbd62d6666e2654c8b510bb04c04cc7fe5
>>>>>>> 03d2b473717304eb575c5825895ef11c3c3ca3b7
