language: node_js
node_js:
  - "stable"
script:
  - npm test
  - npm run build
  - npm run add-domain
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
